import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comment app | vikas Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>

      <div className="text-3xl flex justify-center item-center top-0  bg-slate-500 w-full h-12 pt-1 font-bold fixed">Best Comments</div>

        {children}</body>
    </html>
  );
}
